universe = container
container_image = file:///staging/s/smittal39/tdmpc2_v2.sif
executable = dmc_audit.sh
transfer_input_files = code.tar.gz
arguments = $(args)
transfer_output_files = dmc.tar.gz
transfer_output_remaps = "dmc.tar.gz = results/$(name).tar.gz"
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
log = logs/$(name).log
output = logs/$(name).$(Cluster).out
error = logs/$(name).$(Cluster).err
requirements = (HasCHTCStaging == true)
request_gpus = 1
gpus_minimum_capability = 7.0
gpus_maximum_capability = 9.0
+WantGPULab = true
+GPUJobLength = "short"
request_cpus = 4
request_memory = 24GB
request_disk = 20GB
queue name, args from $(queue_file)
