universe = container
container_image = file:///staging/s/smittal39/tdmpc2_v3.sif
executable = dmc_smoke.sh
transfer_input_files = code.tar.gz
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
log = logs/dmc_smoke.log
output = logs/dmc_smoke.$(Cluster).out
error = logs/dmc_smoke.$(Cluster).err
requirements = (HasCHTCStaging == true)
request_gpus = 1
gpus_minimum_capability = 7.0
gpus_maximum_capability = 12.0
+WantGPULab = true
+GPUJobLength = "short"
request_cpus = 4
request_memory = 24GB
request_disk = 20GB
queue
